version: '3'
services:
  app:
    container_name: course
    restart: always
    build:
      context: .
      dockerfile: docker/go/go.Dockerfile
      args:
        PORT: ${PORT}
    image: course-app:latest
    environment:
      - TZ=Asia/Novosibirsk
    ports:
      - ${PORT}:${PORT}
    networks:
      - network_ext
networks:
  network_ext:
    name: course-net
    driver: bridge