version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: course
    ports:
      - 1488:5432
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: password
      REDIS_USERNAME: admin
    command: ["redis-server", "--requirepass", "password"]